# Enhanced LPO (Arista) - field groups
LPO_EEPROM_FIELD = "LpoEepromField"
LPO_INFO_FIELD = "LpoInfoField"
LPO_VMA_THRESHOLDS_FIELD = "LpoVmaThresholdsField"
LPO_OMA_THRESHOLDS_FIELD = "LpoOmaThresholdsField"
LPO_VMA_FLAGS_FIELD = "LpoVmaFlagsField"
LPO_VMA_DOM_FIELD = "LpoVmaDomField"
LPO_VMA_MASKS_FIELD = "LpoVmaMasksField"
LPO_OMA_FLAGS_FIELD = "LpoOmaFlagsField"
LPO_OMA_DOM_FIELD = "LpoOmaDomField"
LPO_OMA_MASKS_FIELD = "LpoOmaMasksField"

# Enhanced LPO - page 01h advertisement
LPO_EEPROM_COMPLIANCE = "LPOEepromCompliance"
LPO_ENHANCED_SPEC_VERSION = "LPOEnhancedSpecVersion"

# Enhanced LPO - page C1h info / capability
LPO_CAPABILITY = "LPOCapability"
LPO_TX_OUTER_EXTINCTION_RATIO_MAX = "LPOTxOuterExtinctionRatioMax"
LPO_TX_POLARITY_INVERTED = "LPOTxPolarityInverted"
LPO_RX_POLARITY_INVERTED = "LPORxPolarityInverted"
LPO_TX_HOST_INPUT_VMA_MON_ACCURACY = "LPOTxHostInputVMAMonAccuracySupported"
LPO_RX_INPUT_OMA_MON_ACCURACY = "LPORxInputOMAMonAccuracySupported"

# Enhanced LPO - page C1h VMA thresholds
LPO_TX_HOST_INPUT_VMA_HIGH_ALARM_THRESHOLD = "LPOTxHostInputVMAHighAlarmThreshold"
LPO_TX_HOST_INPUT_VMA_LOW_ALARM_THRESHOLD = "LPOTxHostInputVMALowAlarmThreshold"
LPO_TX_HOST_INPUT_VMA_HIGH_WARNING_THRESHOLD = "LPOTxHostInputVMAHighWarningThreshold"
LPO_TX_HOST_INPUT_VMA_LOW_WARNING_THRESHOLD = "LPOTxHostInputVMALowWarningThreshold"

# Enhanced LPO - page C1h OMA thresholds
LPO_RX_INPUT_OMA_HIGH_ALARM_THRESHOLD = "LPORxInputOMAHighAlarmThreshold"
LPO_RX_INPUT_OMA_LOW_ALARM_THRESHOLD = "LPORxInputOMALowAlarmThreshold"
LPO_RX_INPUT_OMA_HIGH_WARNING_THRESHOLD = "LPORxInputOMAHighWarningThreshold"
LPO_RX_INPUT_OMA_LOW_WARNING_THRESHOLD = "LPORxInputOMALowWarningThreshold"

# Enhanced LPO - page C2h VMA flags
LPO_TX_HOST_INPUT_VMA_HIGH_ALARM_FLAG = "LPOTxHostInputVMAHighAlarmFlag"
LPO_TX_HOST_INPUT_VMA_LOW_ALARM_FLAG = "LPOTxHostInputVMALowAlarmFlag"
LPO_TX_HOST_INPUT_VMA_HIGH_WARNING_FLAG = "LPOTxHostInputVMAHighWarningFlag"
LPO_TX_HOST_INPUT_VMA_LOW_WARNING_FLAG = "LPOTxHostInputVMALowWarningFlag"

# Enhanced LPO - page C2h per-lane VMA measurements
LPO_HOST_INPUT_VMA_TX1 = "LPOHostInputVMATx1"
LPO_HOST_INPUT_VMA_TX2 = "LPOHostInputVMATx2"
LPO_HOST_INPUT_VMA_TX3 = "LPOHostInputVMATx3"
LPO_HOST_INPUT_VMA_TX4 = "LPOHostInputVMATx4"
LPO_HOST_INPUT_VMA_TX5 = "LPOHostInputVMATx5"
LPO_HOST_INPUT_VMA_TX6 = "LPOHostInputVMATx6"
LPO_HOST_INPUT_VMA_TX7 = "LPOHostInputVMATx7"
LPO_HOST_INPUT_VMA_TX8 = "LPOHostInputVMATx8"

# Enhanced LPO - page C2h VMA masks
LPO_TX_HOST_INPUT_VMA_HIGH_ALARM_MASK = "LPOTxHostInputVMAHighAlarmMask"
LPO_TX_HOST_INPUT_VMA_LOW_ALARM_MASK = "LPOTxHostInputVMALowAlarmMask"
LPO_TX_HOST_INPUT_VMA_HIGH_WARNING_MASK = "LPOTxHostInputVMAHighWarningMask"
LPO_TX_HOST_INPUT_VMA_LOW_WARNING_MASK = "LPOTxHostInputVMALowWarningMask"

# Enhanced LPO - page C2h OMA flags
LPO_RX_INPUT_OMA_HIGH_ALARM_FLAG = "LPORxInputOMAHighAlarmFlag"
LPO_RX_INPUT_OMA_LOW_ALARM_FLAG = "LPORxInputOMALowAlarmFlag"
LPO_RX_INPUT_OMA_HIGH_WARNING_FLAG = "LPORxInputOMAHighWarningFlag"
LPO_RX_INPUT_OMA_LOW_WARNING_FLAG = "LPORxInputOMALowWarningFlag"

# Enhanced LPO - page C2h per-lane OMA measurements
LPO_INPUT_OMA_RX1 = "LPOInputOMARx1"
LPO_INPUT_OMA_RX2 = "LPOInputOMARx2"
LPO_INPUT_OMA_RX3 = "LPOInputOMARx3"
LPO_INPUT_OMA_RX4 = "LPOInputOMARx4"
LPO_INPUT_OMA_RX5 = "LPOInputOMARx5"
LPO_INPUT_OMA_RX6 = "LPOInputOMARx6"
LPO_INPUT_OMA_RX7 = "LPOInputOMARx7"
LPO_INPUT_OMA_RX8 = "LPOInputOMARx8"

# Enhanced LPO - page C2h OMA masks
LPO_RX_INPUT_OMA_HIGH_ALARM_MASK = "LPORxInputOMAHighAlarmMask"
LPO_RX_INPUT_OMA_LOW_ALARM_MASK = "LPORxInputOMALowAlarmMask"
LPO_RX_INPUT_OMA_HIGH_WARNING_MASK = "LPORxInputOMAHighWarningMask"
LPO_RX_INPUT_OMA_LOW_WARNING_MASK = "LPORxInputOMALowWarningMask"
