# COMMON
ADMIN_INFO_FIELD = "AdminInfo"
ID_FIELD = "Identifier"
VENDOR_NAME_FIELD = "VendorName"
VENDOR_OUI_FIELD = "VendorOUI"
VENDOR_PART_NO_FIELD = "VendorPN"
VENDOR_REV = "VendorRev"
VENDOR_SERIAL_NO = "VendorSN"
VENDOR_DATE = "DateCode"
CONNECTOR_TYPE = "ConnectorType"
MODULE_MEDIA_TYPE = "ModuleMediaType"
HOST_ELECTRICAL_INTERFACE = "HostElectricalInterfaceID"
MODULE_MEDIA_INTERFACE_850NM = "ModuleMediaInterface850nm"
MODULE_MEDIA_INTERFACE_SM = "ModuleMediaInterfaceSM"
MODULE_MEDIA_INTERFACE_PASSIVE_COPPER = "ModuleMediaInterfacePassiveCopper"
MODULE_MEDIA_INTERFACE_ACTIVE_CABLE = "ModuleMediaInterfaceActiveCable"
MODULE_MEDIA_INTERFACE_BASE_T = "ModuleMediaInterfaceBaseT"
LANE_COUNT = "LaneCount"
HOST_LANE_ASSIGNMENT_OPTION = "HostLaneAssignmentOptions"
MEDIA_LANE_ASSIGNMENT_OPTION = "MediaLaneAssignmentOptions"
ACTIVE_APSEL_HOSTLANE_1 = "ActiveSetLane1"
ACTIVE_APSEL_HOSTLANE_2 = "ActiveSetLane2"
ACTIVE_APSEL_HOSTLANE_3 = "ActiveSetLane3"
ACTIVE_APSEL_HOSTLANE_4 = "ActiveSetLane4"
ACTIVE_APSEL_HOSTLANE_5 = "ActiveSetLane5"
ACTIVE_APSEL_HOSTLANE_6 = "ActiveSetLane6"
ACTIVE_APSEL_HOSTLANE_7 = "ActiveSetLane7"
ACTIVE_APSEL_HOSTLANE_8 = "ActiveSetLane8"
MEDIA_INTERFACE_TECH = "MediaInterfaceTechnology"
HW_MAJOR_REV = "ModuleHardwareMajorRevision"
HW_MINOR_REV = "ModuleHardwareMinorRevision"
CMIS_REVISION = "CmisRevision"
ACTIVE_FW_MAJOR_REV = "ModuleActiveFirmwareMajorRevision"
ACTIVE_FW_MINOR_REV = "ModuleActiveFirmwareMinorRevision"
INACTIVE_FW_MAJOR_REV = "ModuleInactiveFirmwareMajorRevision"
INACTIVE_FW_MINOR_REV = "ModuleInactiveFirmwareMinorRevision"

# DOM
TRANS_DOM_FIELD = "TransceiverDom"
CASE_TEMP = "ModuleTemp"
VOLTAGE = "Supply3V3"
RX_POW1 = "Rx1Power"
RX_POW2 = "Rx2Power"
RX_POW3 = "Rx3Power"
RX_POW4 = "Rx4Power"
TX_BIAS1 = "Tx1Bias"
TX_BIAS2 = "Tx2Bias"
TX_BIAS3 = "Tx3Bias"
TX_BIAS4 = "Tx4Bias"
GRID_SPACING = "Tx1SelectedGridSpacing"
LASER_CONFIG_CHANNEL = "Tx1ChannelNumber"
LASER_CURRENT_FREQ = "Tx1CurrentLaserFrequency"
TX_CONFIG_POWER = "Tx1TargetOutputPower"
MEDIA_OUTPUT_LOOPBACK = "MediaSideOutputLoopbackEnable"
MEDIA_INPUT_LOOPBACK = "MediaSideInputLoopbackEnable"
HOST_OUTPUT_LOOPBACK = "HostSideOutputLoopbackEnable"
HOST_INPUT_LOOPBACK = "HostSideLoopbackEnable"
AUX_MON_TYPE = "AuxMonitorType"
AUX1_MON = "Aux1MonValue"
AUX2_MON = "Aux2MonValue"
AUX3_MON = "Aux3MonValue"

# Status
TRANS_STATUS_FIELD = "TransceiverStatus"
MODULE_STATE = "ModuleState"
MODULE_FIRMWARE_FAULT_INFO = "FirmwareFault"
DATAPATH_STATE= "DataPathStateHostLane"
TX_OUTPUT_STATUS = "TxOutputStatus"
RX_OUTPUT_STATUS = "RxOutputStatus"
TX_FAULT_FLAG = "TxFault"
TX_LOS_FLAG = "TxLOS"
TX_CDR_LOL = "TxCDRLOL"
RX_LOS_FLAG = "RxLOS"
RX_CDR_LOL = "RxCDRLOL"
CONFIG_LANE_STATUS = "ConfigStatusLane"
DPINIT_PENDING = "DPInitPending"
TUNING_IN_PROGRESS = "TxTuningInProgress"
WAVELENGTH_UNLOCKED = "TxWavelengthUnlocked"
LASER_TUNING_DETAIL = "TxTuningDetail"


# C-CMIS

## Media Lane FEC Performance Monitoring

## Media Lane Link Performance Monitoring
# PM
TRANS_PM_FIELD = "TransceiverPm"
FREEZE_REQUEST = "FreezeRequest"
MEDIA_LANE_FEC_PM = "Media Lane FEC Performance Monitoring"
MEDIA_LANE_LINK_PM = "Media Lane Link Performance Monitoring"
RX_BITS_PM = "rxBitsPm"
RX_BITS_SUB_INTERVAL_PM = "rxBitsSubIntPm"
RX_CORR_BITS_PM = "rxCorrBitsPm"
RX_MIN_CORR_BITS_SUB_INTERVAL_PM = "rxMinCorrBitsSubIntPm"
RX_MAX_CORR_BITS_SUB_INTERVAL_PM = "rxMaxCorrBitsSubIntPm"
RX_FRAMES_PM = "rxFramesPm"
RX_FRAMES_SUB_INTERVAL_PM = "rxFramsSubIntPm"
RX_FRAMES_UNCORR_ERR_PM = "rxFramesUncorrErrPm"
RX_MIN_FRAMES_UNCORR_ERR_SUB_INTERVAL_PM = "rxMinFramesUncorrErrSubintPm"
RX_MAX_FRAMES_UNCORR_ERR_SUB_INTERVAL_PM = "rxMaxFramesUncorrErrSubintPm"

RX_AVG_CD_PM = "rxAvgCdPm"
RX_MIN_CD_PM = "rxMinCdPm"
RX_MAX_CD_PM = "rxMaxCdPm"
RX_AVG_DGD_PM = "rxAvgDgdPm"
RX_MIN_DGD_PM = "rxMinDgdPm"
RX_MAX_DGD_PM = "rxMaxDgdPm"
RX_AVG_SOPMD_PM = "rxAvgSopmdPm"
RX_MIN_SOPMD_PM = "rxMinSopmdPm"
RX_MAX_SOPMD_PM = "rxMaxSopmdPm"
RX_AVG_PDL_PM = "rxAvgPdlPm"
RX_MIN_PDL_PM = "rxMinPdlPm"
RX_MAX_PDL_PM = "rxMaxPdlPm"
RX_AVG_OSNR_PM = "rxAvgOsnrPm"
RX_MIN_OSNR_PM = "rxMinOsnrPm"
RX_MAX_OSNR_PM = "rxMaxOsnrPm"
RX_AVG_ESNR_PM = "rxAvgEsnrPm"
RX_MIN_ESNR_PM = "rxMinEsnrPm"
RX_MAX_ESNR_PM = "rxMaxEsnrPm"
RX_AVG_CFO_PM = "rxAvgCfoPm"
RX_MAX_CFO_PM = "rxMinCfoPm"
RX_MIN_CFO_PM = "rxMaxCfoPm"
RX_AVG_EVM_PM = "rxAvgEvmPm"
RX_MIN_EVM_PM = "rxMinEvmPm"
RX_MAX_EVM_PM = "rxMaxEvmPm"
TX_AVG_POWER_PM = "txAvgPowerPm"
TX_MIN_POWER_PM = "txMinPowerPm"
TX_MAX_POWER_PM = "txMaxPowerPm"
RX_AVG_POWER_PM = "rxAvgPowerPm"
RX_MIN_POWER_PM = "rxMinPowerPm"
RX_MAX_POWER_PM = "rxMaxPowerPm"
RX_AVG_POWER_PM = "rxAvgPowerPm"
RX_MIN_POWER_PM = "rxMinPowerPm"
RX_MAX_POWER_PM = "rxMaxPowerPm"
RX_AVG_SIG_POWER_PM = "rxAvgSigPowerPm"
RX_MIN_SIG_POWER_PM = "rxMinSigPowerPm"
RX_MAX_SIG_POWER_PM = "rxMaxSigPowerPm"
RX_AVG_SOPROC_PM = "rxAvgSigSoprocPm"
RX_MIN_SOPROC_PM = "rxMinSigSoprocPm"
RX_MAX_SOPROC_PM = "rxMaxSigSoprocPm"
RX_AVG_MER_PM = "rxAvgMerPm"
RX_MIN_MER_PM = "rxMinMerPm"
RX_MAX_MER_PM = "rxMaxMerPm"





