"""
    cmis_page_consts.py

    Constants for CMIS memory map pages
"""

# Constants matching optoe driver
CMIS_EEPROM_PAGE_SIZE = 128
CMIS_NUM_NON_BANKED_PAGES = 16   # pages 00h-0Fh
CMIS_ARCH_PAGES = 256            # architectural pages per bank (matches OPTOE_ARCH_PAGES)

# CMIS page number constants
ADMINISTRATIVE_PAGE = 0x00
ADVERTISING_PAGE = 0x01
THRESHOLDS_PAGE = 0x02
LANE_DATAPATH_CONFIG_PAGE = 0x10
LANE_DATAPATH_STATUS_PAGE = 0x11
TUNABLE_LASER_CTRL_STATUS_PAGE = 0x12
MODULE_PERF_DIAG_CTRL_PAGE = 0x13
VDM_ADVERTISING_CTRL_PAGE = 0x2F
CDB_MESSAGE_PAGE = 0x9F

