"""
    page42.py

    C-CMIS Page 42h - Performance Monitoring Advertisement.

    Advertises which Page 34h/35h performance monitors are implemented by the
    module. All fields are global (non-banked) capability bits.
"""

from .page import CmisPage
from .....fields.xcvr_field import NumberRegField, RegBitField
from .....fields import consts


class CCmisPmAdvertisementPage(CmisPage):
    """C-CMIS Page 42h: performance-monitoring "Impl" advertisement bits."""

    def __init__(self, codes, bank=0, page=0x42):
        super().__init__(codes, page=page, bank=bank)

        self.fields[consts.PM_ADVT_FIELD] = [
            NumberRegField("PmAdvtByte128", self.getaddr(128),
                RegBitField(consts.RX_MAX_CORR_BITS_SUB_INTERVAL_PM_IMPL, 4),
                RegBitField(consts.RX_MIN_CORR_BITS_SUB_INTERVAL_PM_IMPL, 3),
                RegBitField(consts.RX_CORR_BITS_PM_IMPL, 2),
                RegBitField(consts.RX_BITS_SUB_INTERVAL_PM_IMPL, 1),
                RegBitField(consts.RX_BITS_PM_IMPL, 0),
            ),
            NumberRegField("PmAdvtByte129", self.getaddr(129),
                RegBitField(consts.RX_MAX_FRAMES_UNCORR_ERR_SUB_INTERVAL_PM_IMPL, 4),
                RegBitField(consts.RX_MIN_FRAMES_UNCORR_ERR_SUB_INTERVAL_PM_IMPL, 3),
                RegBitField(consts.RX_FRAMES_UNCORR_ERR_PM_IMPL, 2),
                RegBitField(consts.RX_FRAMES_SUB_INTERVAL_PM_IMPL, 1),
                RegBitField(consts.RX_FRAMES_PM_IMPL, 0),
            ),
            NumberRegField("PmAdvtByte130", self.getaddr(130),
                RegBitField(consts.RX_CD_IMPL, 7),
                RegBitField(consts.RX_AVG_CD_PM_IMPL, 6),
                RegBitField(consts.RX_MIN_CD_PM_IMPL, 5),
                RegBitField(consts.RX_MAX_CD_PM_IMPL, 4),
                RegBitField(consts.RX_DGD_IMPL, 3),
                RegBitField(consts.RX_AVG_DGD_PM_IMPL, 2),
                RegBitField(consts.RX_MIN_DGD_PM_IMPL, 1),
                RegBitField(consts.RX_MAX_DGD_PM_IMPL, 0),
            ),
            NumberRegField("PmAdvtByte131", self.getaddr(131),
                RegBitField(consts.RX_LG_SOPMD_IMPL, 7),
                RegBitField(consts.RX_AVG_LG_SOPMD_PM_IMPL, 6),
                RegBitField(consts.RX_MIN_LG_SOPMD_PM_IMPL, 5),
                RegBitField(consts.RX_MAX_LG_SOPMD_PM_IMPL, 4),
                RegBitField(consts.RX_PDL_IMPL, 3),
                RegBitField(consts.RX_AVG_PDL_PM_IMPL, 2),
                RegBitField(consts.RX_MIN_PDL_PM_IMPL, 1),
                RegBitField(consts.RX_MAX_PDL_PM_IMPL, 0),
            ),
            NumberRegField("PmAdvtByte132", self.getaddr(132),
                RegBitField(consts.RX_OSNR_IMPL, 7),
                RegBitField(consts.RX_AVG_OSNR_PM_IMPL, 6),
                RegBitField(consts.RX_MIN_OSNR_PM_IMPL, 5),
                RegBitField(consts.RX_MAX_OSNR_PM_IMPL, 4),
                RegBitField(consts.RX_ESNR_IMPL, 3),
                RegBitField(consts.RX_AVG_ESNR_PM_IMPL, 2),
                RegBitField(consts.RX_MIN_ESNR_PM_IMPL, 1),
                RegBitField(consts.RX_MAX_ESNR_PM_IMPL, 0),
            ),
            NumberRegField("PmAdvtByte133", self.getaddr(133),
                RegBitField(consts.RX_CFO_IMPL, 7),
                RegBitField(consts.RX_AVG_CFO_PM_IMPL, 6),
                RegBitField(consts.RX_MIN_CFO_PM_IMPL, 5),
                RegBitField(consts.RX_MAX_CFO_PM_IMPL, 4),
                RegBitField(consts.RX_EVM_IMPL, 3),
                RegBitField(consts.RX_AVG_EVM_PM_IMPL, 2),
                RegBitField(consts.RX_MIN_EVM_PM_IMPL, 1),
                RegBitField(consts.RX_MAX_EVM_PM_IMPL, 0),
            ),
            NumberRegField("PmAdvtByte134", self.getaddr(134),
                RegBitField(consts.RX_SOPROC_IMPL, 7),
                RegBitField(consts.RX_AVG_SOPROC_PM_IMPL, 6),
                RegBitField(consts.RX_MIN_SOPROC_PM_IMPL, 5),
                RegBitField(consts.RX_MAX_SOPROC_PM_IMPL, 4),
                RegBitField(consts.TX_POWER_IMPL, 3),
                RegBitField(consts.TX_AVG_POWER_PM_IMPL, 2),
                RegBitField(consts.TX_MIN_POWER_PM_IMPL, 1),
                RegBitField(consts.TX_MAX_POWER_PM_IMPL, 0),
            ),
            NumberRegField("PmAdvtByte135", self.getaddr(135),
                RegBitField(consts.RX_POWER_IMPL, 7),
                RegBitField(consts.RX_AVG_POWER_PM_IMPL, 6),
                RegBitField(consts.RX_MIN_POWER_PM_IMPL, 5),
                RegBitField(consts.RX_MAX_POWER_PM_IMPL, 4),
                RegBitField(consts.RX_SIG_POWER_IMPL, 3),
                RegBitField(consts.RX_AVG_SIG_POWER_PM_IMPL, 2),
                RegBitField(consts.RX_MIN_SIG_POWER_PM_IMPL, 1),
                RegBitField(consts.RX_MAX_SIG_POWER_PM_IMPL, 0),
            ),
            NumberRegField("PmAdvtByte136", self.getaddr(136),
                RegBitField(consts.RX_MEDIA_FED_PM_IMPL, 1),
                RegBitField(consts.RX_MEDIA_FDD_PM_IMPL, 0),
            ),
            NumberRegField("PmAdvtByte137", self.getaddr(137),
                RegBitField(consts.TX_HOST_FED_PM_IMPL, 1),
                RegBitField(consts.TX_HOST_FDD_PM_IMPL, 0),
            ),
            NumberRegField("PmAdvtByte138", self.getaddr(138),
                RegBitField(consts.RX_CLOCK_REC_IMPL, 7),
                RegBitField(consts.RX_AVG_CLOCK_REC_PM_IMPL, 6),
                RegBitField(consts.RX_MIN_CLOCK_REC_PM_IMPL, 5),
                RegBitField(consts.RX_MAX_CLOCK_REC_PM_IMPL, 4),
                RegBitField(consts.RX_HG_SOPMD_IMPL, 3),
                RegBitField(consts.RX_AVG_HG_SOPMD_PM_IMPL, 2),
                RegBitField(consts.RX_MIN_HG_SOPMD_PM_IMPL, 1),
                RegBitField(consts.RX_MAX_HG_SOPMD_PM_IMPL, 0),
            ),
            NumberRegField("PmAdvtByte139", self.getaddr(139),
                RegBitField(consts.RX_SNR_MARGIN_IMPL, 7),
                RegBitField(consts.RX_AVG_SNR_MARGIN_PM_IMPL, 6),
                RegBitField(consts.RX_MIN_SNR_MARGIN_PM_IMPL, 5),
                RegBitField(consts.RX_MAX_SNR_MARGIN_PM_IMPL, 4),
                RegBitField(consts.RX_MER_IMPL, 3),
                RegBitField(consts.RX_AVG_MER_PM_IMPL, 2),
                RegBitField(consts.RX_MIN_MER_PM_IMPL, 1),
                RegBitField(consts.RX_MAX_MER_PM_IMPL, 0),
            ),
            NumberRegField("PmAdvtByte140", self.getaddr(140),
                RegBitField(consts.RX_QFACTOR_IMPL, 7),
                RegBitField(consts.RX_AVG_QFACTOR_PM_IMPL, 6),
                RegBitField(consts.RX_MIN_QFACTOR_PM_IMPL, 5),
                RegBitField(consts.RX_MAX_QFACTOR_PM_IMPL, 4),
                RegBitField(consts.RX_QMARGIN_IMPL, 3),
                RegBitField(consts.RX_AVG_QMARGIN_PM_IMPL, 2),
                RegBitField(consts.RX_MIN_QMARGIN_PM_IMPL, 1),
                RegBitField(consts.RX_MAX_QMARGIN_PM_IMPL, 0),
            ),
        ]
