#!/usr/bin/env python2

"""
    pcied
    PCIe device monitoring daemon for SONiC
"""

try:
    import os
    import signal
    import subprocess
    import sys
    import threading

    import swsssdk
    from sonic_py_common.daemon_base import DaemonBase
    from sonic_py_common import device_info
except ImportError as e:
    raise ImportError(str(e) + " - required module not found")

#
# Constants ====================================================================
#
SYSLOG_IDENTIFIER = "pcied"

PCIE_RESULT_REGEX = "PCIe Device Checking All Test"
PCIE_TABLE_NAME = "PCIE_STATUS"

PCIE_CONF_FILE = 'pcie.yaml'

PCIED_MAIN_THREAD_SLEEP_SECS = 60
REDIS_HOSTIP = "127.0.0.1"

#
# Daemon =======================================================================
#


class DaemonPcied(DaemonBase):
    def __init__(self, log_identifier):
        super(DaemonPcied, self).__init__(log_identifier)

        (platform_path, _) = device_info.get_paths_to_platform_and_hwsku_dirs()
        pciefilePath = os.path.join(platform_path, "plugins", PCIE_CONF_FILE)
        sys.path.append(os.path.abspath(pciefilePath))
        if not os.path.exists(pciefilePath):
            self.log_error("Platform pcie configuration file doesn't exist! Exiting ...")
            sys.exit("Platform PCIe Configuration file doesn't exist!")

        self.timeout = PCIED_MAIN_THREAD_SLEEP_SECS
        self.stop_event = threading.Event()

        self.state_db = swsssdk.SonicV2Connector(host=REDIS_HOSTIP)
        self.state_db.connect("STATE_DB")

    # Check the PCIe devices
    def check_pcie_devices(self):
        try:
            platform_path, _ = device_info.get_paths_to_platform_and_hwsku_dirs()
            platform_plugins_path = os.path.join(platform_path, "plugins")
            sys.path.append(os.path.abspath(platform_plugins_path))
            from pcieutil import PcieUtil
        except ImportError as e:
            self.log_warning("Failed to load platform-specific PcieUtil module. Falling back to the common implementation")
            try:
                from sonic_platform_base.sonic_pcie.pcie_common import PcieUtil
                platform_pcieutil = PcieUtil(platform_plugins_path)
            except ImportError as e:
                self.log_error("Failed to load default PcieUtil module. Error : {}".format(str(e)), True)
                raise e

        resultInfo = platform_pcieutil.get_pcie_check()
        err = 0

        for item in resultInfo:
            if item["result"] == "Failed":
                self.log_warning("PCIe Device: " + item["name"] + " Not Found")
                err += 1

        if err:
            self.update_state_db("PCIE_DEVICES", "status", "FAILED")
            self.log_error("PCIe device status check : FAILED")
        else:
            self.update_state_db("PCIE_DEVICES", "status", "PASSED")
            self.log_info("PCIe device status check : PASSED")

    def read_state_db(self, key1, key2):
        return self.state_db.get('STATE_DB', key1, key2)

    def update_state_db(self, key1, key2, value):
        self.state_db.set('STATE_DB', key1, key2, value)

    # Signal handler
    def signal_handler(self, sig, frame):
        if sig == signal.SIGHUP:
            self.log_info("Caught SIGHUP - ignoring...")
        elif sig == signal.SIGINT:
            self.log_info("Caught SIGINT - exiting...")
            self.stop_event.set()
        elif sig == signal.SIGTERM:
            self.log_info("Caught SIGTERM - exiting...")
            self.stop_event.set()
        else:
            self.log_warning("Caught unhandled signal '" + sig + "'")

    # Initialize daemon
    def init(self):
        self.log_info("Start daemon init...")

    # Deinitialize daemon
    def deinit(self):
        self.log_info("Start daemon deinit...")

    # Run daemon
    def run(self):
        self.log_info("Starting up...")

        # Start daemon initialization sequence
        self.init()

        # Start main loop
        self.log_info("Start daemon main loop")

        while not self.stop_event.wait(self.timeout):
            # Check the Pcie device status
            self.check_pcie_devices()

        self.log_info("Stop daemon main loop")

        # Start daemon deinitialization sequence
        self.deinit()

        self.log_info("Shutting down...")

#
# Main =========================================================================
#


def main():
    pcied = DaemonPcied(SYSLOG_IDENTIFIER)
    pcied.run()

if __name__ == '__main__':
    main()
