name: Test sonic-xcvr with xcvr-emu

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: test sonic-xcvr with xcvr-emu
      run: make test_sonic_xcvr_with_emu
